//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerencianet.SDK.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gerencianet.SDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {
        ///  &quot;CreateCharge&quot;: {
        ///    &quot;route&quot;: &quot;/charge&quot;,
        ///    &quot;method&quot;: &quot;POST&quot;
        ///  },
        ///  &quot;DetailCharge&quot;: {
        ///    &quot;route&quot;: &quot;/charge/:id&quot;,
        ///    &quot;method&quot;: &quot;GET&quot;
        ///  },
        ///  &quot;UpdateChargeMetadata&quot;: {
        ///    &quot;route&quot;: &quot;/charge/:id/metadata&quot;,
        ///    &quot;method&quot;: &quot;PUT&quot;
        ///  },
        ///  &quot;UpdateBillet&quot;: {
        ///    &quot;route&quot;: &quot;/charge/:id/billet&quot;,
        ///    &quot;method&quot;: &quot;PUT&quot;
        ///  },
        ///  &quot;PayCharge&quot;: {
        ///    &quot;route&quot;: &quot;/charge/:id/pay&quot;,
        ///    &quot;method&quot;: &quot;POST&quot;
        ///  },
        ///  &quot;CancelCharge&quot;: {
        ///    &quot;route&quot;: &quot;/charge/:id/cancel&quot;,
        ///    &quot;method&quot;: &quot;PUT&quot;
        ///  },
        ///  &quot;CreateCarnet&quot;: [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string endpoints {
            get {
                return ResourceManager.GetString("endpoints", resourceCulture);
            }
        }
    }
}
